// <auto-generated />
using System;
using CarbonSim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarbonSim.Data.Migrations
{
    [DbContext(typeof(CarbonSimDbContext))]
    [Migration("20260917041356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("CarbonSim.Data.Accounts.PlayerAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResetCodeAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ResetCodeExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetCodeHash")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique()
                        .HasFilter("\"CompanyName\" IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AbatementMenuRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualNetRevenuePerTonne")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualReductionShare")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImplementationYears")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LifetimeYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UpfrontCostPerTonne")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Sector", "Code");

                    b.ToTable("AbatementMenu", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AbatementOptionRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualNetRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualReduction")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImplementationYears")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LifetimeYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UpfrontCost")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "UnitId", "Code");

                    b.ToTable("AbatementOptions", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AllocationYearRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cap")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FreeAllocation")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Year");

                    b.ToTable("AllocationYears", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionAwardRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Year", "Sequence", "Vintage", "BidId");

                    b.ToTable("AuctionAwards", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionBidRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "Year", "Sequence", "BidId");

                    b.HasIndex("SimulationId", "CompanyId");

                    b.ToTable("AuctionBids", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionLotRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsForward")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Year", "Sequence", "Vintage");

                    b.ToTable("AuctionLots", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnsoldVolume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Year", "Sequence");

                    b.ToTable("Auctions", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionRejectedBidRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "Year", "Sequence", "Vintage", "BidId");

                    b.ToTable("AuctionRejectedBids", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionResultRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ClearingPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OfferedVolume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Year", "Sequence", "Vintage");

                    b.ToTable("AuctionResults", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BausGrowthRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BausGrowthId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxAnnualRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinAnnualRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingSystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "BausGrowthId");

                    b.HasIndex("SimulationId", "TradingSystemId");

                    b.ToTable("BausGrowthBands", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BookTradeRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuyOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<long>("SellOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "ProductKind", "Vintage", "Sequence");

                    b.ToTable("BookTrades", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotBidSectionRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Section")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "BotId", "Year", "Section");

                    b.ToTable("BotBidSections", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AbatementMargin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BidPriceNoise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BidVolumeFraction")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectedPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OffsetDiscount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReservationPriceFactor")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "BotId");

                    b.HasIndex("SimulationId", "CompanyId");

                    b.ToTable("Bots", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotTriggerDoneRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "BotId", "Year", "Trigger");

                    b.ToTable("BotTriggerDone", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotTriggerTimeRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AtFractionOfYear")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "BotId", "Trigger");

                    b.ToTable("BotTriggerTimes", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotUnitRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "BotId", "UnitId");

                    b.ToTable("BotUnits", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.CashMovementRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "Sequence");

                    b.ToTable("CashMovements", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ClockRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AuctionNotice")
                        .HasColumnType("TEXT");

                    b.Property<int>("CloseNoticedThrough")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClosedThrough")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Elapsed")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("HaltAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HaltedForYearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenNoticedThrough")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenedThrough")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PauseAfterAuction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RunningSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId");

                    b.ToTable("Clocks", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.CompanyComplianceRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllowancesSurrendered")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Banked")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Forfeited")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Obligation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OffsetsSurrendered")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PenaltyAllowanceDebit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PenaltyCash")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shortfall")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Year", "CompanyId");

                    b.HasIndex("SimulationId", "CompanyId");

                    b.ToTable("CompanyCompliances", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.CompanyRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Capital")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EscrowedCash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OverdraftLimit")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "CompanyId");

                    b.HasIndex("SimulationId", "OwnerPlayerId");

                    b.HasIndex("SimulationId", "Sector");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ExchangeRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId");

                    b.ToTable("Exchanges", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.FineRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "FineId");

                    b.HasIndex("SimulationId", "UnitId");

                    b.ToTable("Fines", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.GovernmentIssuedRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Vintage");

                    b.ToTable("GovernmentIssued", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.GovernmentRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasIssued")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId");

                    b.ToTable("Government", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.GovernmentReserveRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Vintage");

                    b.ToTable("GovernmentReserves", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ImplementedAbatementRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OptionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpiresAfterYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImplementedIn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatingFromYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "UnitId", "OptionIndex");

                    b.ToTable("ImplementedAbatements", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.JournalTradeRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellerCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "Sequence");

                    b.HasIndex("SimulationId", "BuyerCompanyId");

                    b.ToTable("JournalTrades", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.LedgerAvailableRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "CompanyId", "ProductKind", "Vintage");

                    b.ToTable("LedgerAvailable", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.LedgerEscrowedRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "CompanyId", "ProductKind", "Vintage");

                    b.ToTable("LedgerEscrowed", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.LedgerGrantedYearRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "Year");

                    b.ToTable("LedgerGrantedYears", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.OrderBookRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LastTradePrice")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "ProductKind", "Vintage");

                    b.ToTable("OrderBooks", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.OrderRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EscrowedCash")
                        .HasColumnType("TEXT");

                    b.Property<int>("FillPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FilledVolume")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "OrderId");

                    b.HasIndex("SimulationId", "CompanyId");

                    b.HasIndex("SimulationId", "UnitId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.OtcOfferRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OfferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellerUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "OfferId");

                    b.ToTable("OtcOffers", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ParametersRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualCapReductionRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AuctionCeilingPrice")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AuctionDuration")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AuctionFloorPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuctionsPerYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BankingLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cap")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FreeAllocationShare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OffsetUsageLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OverdraftInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PenaltyAllowanceDebit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PenaltyPerTonne")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TradingOpenShareOfYear")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolatilityBand")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("YearLength")
                        .HasColumnType("TEXT");

                    b.Property<int>("Years")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "TradingSystemId");

                    b.ToTable("Parameters", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.PlayerRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "PlayerId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ReconciledCompanyYearRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "CompanyId", "Year");

                    b.ToTable("ReconciledCompanyYears", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.SectorRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmissionShare")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "Name");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ShutdownRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId", "UnitId", "Year");

                    b.ToTable("UnitShutdowns", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.SimulationRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("RandomState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationId");

                    b.ToTable("Simulations", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.TradingSystemRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "TradingSystemId");

                    b.HasIndex("SimulationId")
                        .IsUnique();

                    b.ToTable("TradingSystems", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.UnitAllocationRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BausGrowth")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "UnitId");

                    b.ToTable("UnitAllocations", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.UnitAllocationYearRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BausEmissions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FreeAllocation")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "UnitId", "Year");

                    b.ToTable("UnitAllocationYears", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.UnitRecord", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoTrade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaselineEmissions")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NormalOperatingProfit")
                        .HasColumnType("TEXT");

                    b.HasKey("SimulationId", "UnitId");

                    b.HasIndex("SimulationId", "CompanyId");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AbatementMenuRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SectorRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "Sector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AbatementOptionRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.UnitRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AllocationYearRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionAwardRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.AuctionResultRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "Year", "Sequence", "Vintage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionBidRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarbonSim.Data.Persistence.AuctionRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "Year", "Sequence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionLotRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.AuctionRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "Year", "Sequence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionRejectedBidRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.AuctionResultRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "Year", "Sequence", "Vintage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.AuctionResultRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.AuctionRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "Year", "Sequence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BausGrowthRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.ParametersRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "TradingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BookTradeRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.OrderBookRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "ProductKind", "Vintage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotBidSectionRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.BotRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotTriggerDoneRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.BotRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotTriggerTimeRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.BotRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.BotUnitRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.BotRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.CashMovementRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ClockRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.CompanyComplianceRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.CompanyRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarbonSim.Data.Persistence.PlayerRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "OwnerPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarbonSim.Data.Persistence.SectorRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "Sector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ExchangeRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.FineRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.UnitRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.GovernmentIssuedRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.GovernmentRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.GovernmentRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.GovernmentReserveRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.GovernmentRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ImplementedAbatementRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.UnitRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.JournalTradeRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "BuyerCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.LedgerAvailableRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.LedgerEscrowedRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.LedgerGrantedYearRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.OrderBookRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.ExchangeRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.OrderRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarbonSim.Data.Persistence.UnitRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.OtcOfferRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ParametersRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.TradingSystemRecord", null)
                        .WithOne("Parameters")
                        .HasForeignKey("CarbonSim.Data.Persistence.ParametersRecord", "SimulationId", "TradingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.PlayerRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ReconciledCompanyYearRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.SectorRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.ShutdownRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.UnitRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.TradingSystemRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.SimulationRecord", null)
                        .WithOne("TradingSystem")
                        .HasForeignKey("CarbonSim.Data.Persistence.TradingSystemRecord", "SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.UnitAllocationRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.UnitRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.UnitAllocationYearRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.UnitAllocationRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.UnitRecord", b =>
                {
                    b.HasOne("CarbonSim.Data.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("SimulationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.SimulationRecord", b =>
                {
                    b.Navigation("TradingSystem");
                });

            modelBuilder.Entity("CarbonSim.Data.Persistence.TradingSystemRecord", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
